### PR TITLE
Add ability to manage files on member research data page 

### PR DESCRIPTION
**Pull request by beaugunderson**

### CODE REVIEW

**Comment by BenjaminHCCarr** [comment]
Is this WIP Pull the ability to publicly share individual "data selfies"?

**Comment by beaugunderson** [comment]
@BenjaminHCCarr no, this work is to allow the files that direct-sharing projects upload back to a member's profile to show up on that member's profile :)

**Comment by BenjaminHCCarr** [comment]
Great, thanks for the update @beaugunderson

**Comment by beaugunderson** [comment]
merging as discussed on Slack :)

**Pull request merged**
